(in-package #:plugger-test)
(define-test load-plugins
  (multiple-value-bind (success loaded) (load-plugins "test_plugins/load" :included-plugins nil)
    (assert-equal success 0)
    (assert-equal loaded nil))
  (multiple-value-bind (success loaded) (load-plugins "test_plugins/load")
    (assert-equal success 1)
    (assert-equal loaded '(("plugin" . success))))
  (multiple-value-bind (success loaded) (load-plugins "test_plugins/load" :excluded-plugins '("plugin"))
    (assert-equal success 0)
    (assert-equal loaded nil))
  (multiple-value-bind (success loaded) (load-plugins "test_plugins/load-failure")
    (assert-equal success 0)
    (assert-equal loaded '(("plugin" . error))))
  (multiple-value-bind (success loaded) (load-plugins "test_plugins/load-order" :load-order-test #'string<)
    (assert success 2)
    (assert-equal loaded '(("a" . success)
                           ("b" . success))))
  (assert-error 'error (load-plugins "test_plugins/load-failure" :die-on-error)))
